package gr.cons.nancy.lang;/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import gr.cons.nancy.lang.App;
import org.junit.Assert;
import org.junit.Test;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
//        Assert.assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
